import * as path from 'path';
import { Module } from '@nestjs/common';
import { GraphQLModule } from '@nestjs/graphql';
import { MercuriusDriver, MercuriusDriverConfig } from '@nestjs/mercurius';

import { AppController } from './app.controller';
import { AppService } from './app.service';
import { OAuthClientsModule } from './resources/oauth-clients/oauth-clients.module'
import { OAuthRedirectUrisModule } from './resources/oauth-redirect-uris/oauth-redirect-uris.module'
import { OAuthScopesModule } from './resources/oauth-scopes/oauth-scopes.module'
import { OAuthCodesModule } from './resources/oauth-codes/oauth-codes.module'
import { OAuthTokensModule } from './resources/oauth-tokens/oauth-tokens.module'

@Module({
  imports: [
    GraphQLModule.forRoot<MercuriusDriverConfig>({
      driver: MercuriusDriver,
      autoSchemaFile: path.join(__dirname, './autogenerated-schema.gql'),
      graphiql: process.env.NODE_ENV === 'development',
    }),
    OAuthClientsModule,
    OAuthRedirectUrisModule,
    OAuthScopesModule,
    OAuthCodesModule,
    OAuthTokensModule,
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
